language: node_js
sudo: false

node_js:
  - "9"
  - "8"

notifications:
  email:
    recipents:
      - vgerbot@gmail.com
  on_success: change
  on_failure: always

install:
  - npm i

script:
  - npm run test:node
  - npm run ci
after_success:
  npm run codecov
